# Logfile created on 2017-09-19 18:06:23 +0100 by logger.rb/56815
E, [2017-09-19T18:06:30.255120 #16868] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Started reports: 5"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-19T18:06:30.519107 #16868] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Reports with performance data: 3"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-19T18:06:30.664702 #16868] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Reports with Outage data: 3"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-19T18:06:30.672446 #16868] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Uptime: 90052"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-19T18:06:30.675072 #16868] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Downtime: 1905"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-19T18:06:30.676021 #16868] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Uptime: 77809"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-19T18:06:30.678267 #16868] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Downtime: 985"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-19T18:06:30.683447 #16868] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Uptime: 94647"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-19T18:06:30.686652 #16868] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Downtime: 5544"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-19T18:06:30.687690 #16868] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Uptime: 77809"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-19T18:06:30.689758 #16868] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Downtime: 985"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-19T18:06:30.694853 #16868] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Uptime: 82220"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-19T18:06:30.701251 #16868] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Downtime: 4386"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-19T18:06:30.702232 #16868] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Uptime: 77809"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-19T18:06:30.703643 #16868] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Downtime: 985"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T09:13:16.145150 #3664] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Started reports: 5"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T09:13:16.394196 #3664] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Reports with performance data: 3"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T09:13:16.537976 #3664] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Reports with Outage data: 3"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T09:13:16.549103 #3664] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Uptime: 82561"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T09:13:16.552422 #3664] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Downtime: 3839"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T09:13:16.554518 #3664] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Uptime: 77648"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T09:13:16.556804 #3664] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Downtime: 130"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T09:13:16.561351 #3664] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Uptime: 83832"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T09:13:16.563832 #3664] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Downtime: 2568"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T09:13:16.564956 #3664] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Uptime: 77648"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T09:13:16.567194 #3664] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Downtime: 130"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T09:13:16.575152 #3664] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Uptime: 83626"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T09:13:16.577814 #3664] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Downtime: 2774"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T09:13:16.578961 #3664] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Uptime: 77648"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T09:13:16.580421 #3664] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Downtime: 130"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:19:35.678416 #13952] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Started reports: 5"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:20:34.383766 #14013] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Started reports: 5"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:21:11.602733 #14047] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Started reports: 5"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:21:11.840135 #14047] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Reports with performance data: 3"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:21:12.002675 #14047] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Reports with Outage data: 3"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:22:06.691208 #14091] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Started reports: 5"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:22:06.942600 #14091] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Reports with performance data: 3"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:22:07.117755 #14091] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Reports with Outage data: 3"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:22:45.742931 #14130] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Started reports: 5"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:22:45.990856 #14130] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Reports with performance data: 3"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:22:46.186719 #14130] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Reports with Outage data: 3"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:22:46.197826 #14130] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Uptime: 81189"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:22:46.225221 #14130] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Downtime: 2018"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:23:07.630252 #14158] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Started reports: 5"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:23:07.868894 #14158] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Reports with performance data: 3"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:23:08.074152 #14158] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Reports with Outage data: 3"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:23:08.082660 #14158] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Uptime: 81919"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:23:08.086412 #14158] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Downtime: 2141"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:23:08.088097 #14158] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Uptime: 81919"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:23:08.090197 #14158] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Downtime: 2141"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:23:08.093818 #14158] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Uptime: 81919"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:23:08.096722 #14158] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Downtime: 2141"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:23:08.097826 #14158] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Uptime: 81919"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:23:08.099445 #14158] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Downtime: 2141"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:23:08.107229 #14158] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Uptime: 81919"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:23:08.113217 #14158] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Downtime: 2141"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:23:08.114256 #14158] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Uptime: 81919"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:23:08.115543 #14158] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Downtime: 2141"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:24:24.492833 #14188] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Started reports: 5"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:24:24.724577 #14188] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Reports with performance data: 3"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:24:24.929503 #14188] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Reports with Outage data: 3"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:24:24.935199 #14188] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Uptime: 78216"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:24:24.938122 #14188] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Downtime: 4895"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:24:24.941198 #14188] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Unmonitored: 3289"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:24:24.942371 #14188] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Uptime: 78216"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:24:24.943524 #14188] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Downtime: 4895"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:24:24.945253 #14188] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Unmonitored: 3289"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:24:24.950546 #14188] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Uptime: 78216"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:24:24.953325 #14188] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Downtime: 4895"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:24:24.956315 #14188] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Unmonitored: 3289"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:24:24.957405 #14188] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Uptime: 78216"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:24:24.958341 #14188] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Downtime: 4895"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:24:24.959892 #14188] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Unmonitored: 3289"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:24:24.962493 #14188] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Uptime: 78216"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:24:24.965244 #14188] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Downtime: 4895"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:24:24.967979 #14188] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Unmonitored: 3289"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:24:24.968994 #14188] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Uptime: 78216"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:24:24.970152 #14188] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Downtime: 4895"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:24:24.971401 #14188] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Unmonitored: 3289"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:25:02.505537 #14213] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Started reports: 5"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:25:02.740307 #14213] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Reports with performance data: 3"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:25:02.896403 #14213] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Reports with Outage data: 3"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:25:02.902364 #14213] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Uptime: 82744"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:25:02.904815 #14213] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Downtime: 2560"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:25:02.907271 #14213] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Unmonitored: 1096"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:25:02.908334 #14213] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Uptime: 82744"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:25:02.909384 #14213] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Downtime: 2560"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:25:02.911037 #14213] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Unmonitored: 1096"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:25:02.914003 #14213] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Uptime: 82744"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:25:02.916646 #14213] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Downtime: 2560"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:25:02.918840 #14213] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Unmonitored: 1096"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:25:02.919933 #14213] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Uptime: 82744"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:25:02.920914 #14213] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Downtime: 2560"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:25:02.922451 #14213] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Unmonitored: 1096"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:25:02.925505 #14213] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Uptime: 82744"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:25:02.928022 #14213] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Downtime: 2560"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:25:02.930398 #14213] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Unmonitored: 1096"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:25:02.931367 #14213] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Uptime: 82744"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:25:02.932293 #14213] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Downtime: 2560"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:25:02.932822 #14213] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Unmonitored: 1096"]
ArgumentError wrong number of arguments (given 1, expected 0)
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch.rb:28:in `logger'
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
I, [2017-09-20T15:32:24.881046 #14363]  INFO -- : Started reports: 5
I, [2017-09-20T15:32:25.138554 #14363]  INFO -- : Reports with performance data: 3
I, [2017-09-20T15:32:25.376612 #14363]  INFO -- : Reports with Outage data: 3
I, [2017-09-20T15:32:25.382377 #14363]  INFO -- : Uptime: 78404
I, [2017-09-20T15:32:25.385202 #14363]  INFO -- : Downtime: 3551
I, [2017-09-20T15:32:25.388649 #14363]  INFO -- : Unmonitored: 4445
I, [2017-09-20T15:32:25.389676 #14363]  INFO -- : Performance Uptime: 78404
I, [2017-09-20T15:32:25.390566 #14363]  INFO -- : Performance Downtime: 3551
I, [2017-09-20T15:32:25.392119 #14363]  INFO -- : Performance Unmonitored: 4445
I, [2017-09-20T15:32:25.395537 #14363]  INFO -- : Uptime: 78404
I, [2017-09-20T15:32:25.398709 #14363]  INFO -- : Downtime: 3551
I, [2017-09-20T15:32:25.402173 #14363]  INFO -- : Unmonitored: 4445
I, [2017-09-20T15:32:25.403178 #14363]  INFO -- : Performance Uptime: 78404
I, [2017-09-20T15:32:25.404211 #14363]  INFO -- : Performance Downtime: 3551
I, [2017-09-20T15:32:25.405749 #14363]  INFO -- : Performance Unmonitored: 4445
I, [2017-09-20T15:32:25.409098 #14363]  INFO -- : Uptime: 78404
I, [2017-09-20T15:32:25.412343 #14363]  INFO -- : Downtime: 3551
I, [2017-09-20T15:32:25.415825 #14363]  INFO -- : Unmonitored: 4445
I, [2017-09-20T15:32:25.416882 #14363]  INFO -- : Performance Uptime: 78404
I, [2017-09-20T15:32:25.417941 #14363]  INFO -- : Performance Downtime: 3551
I, [2017-09-20T15:32:25.418539 #14363]  INFO -- : Performance Unmonitored: 4445
E, [2017-09-20T15:33:24.528406 #14396] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Started reports: 5"]
NoMethodError undefined method `new' for #<Logger:0x00000003d09bb8>
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:33:24.816314 #14396] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Reports with performance data: 3"]
NoMethodError undefined method `new' for #<Logger:0x00000003d09bb8>
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:33:24.983486 #14396] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Reports with Outage data: 3"]
NoMethodError undefined method `new' for #<Logger:0x00000003d09bb8>
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:33:24.992573 #14396] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Uptime: 82176"]
NoMethodError undefined method `new' for #<Logger:0x00000003d09bb8>
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:33:24.997629 #14396] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Downtime: 1615"]
NoMethodError undefined method `new' for #<Logger:0x00000003d09bb8>
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:33:25.002603 #14396] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Unmonitored: 2609"]
NoMethodError undefined method `new' for #<Logger:0x00000003d09bb8>
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:33:25.006220 #14396] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Uptime: 82176"]
NoMethodError undefined method `new' for #<Logger:0x00000003d09bb8>
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:33:25.009541 #14396] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Downtime: 1615"]
NoMethodError undefined method `new' for #<Logger:0x00000003d09bb8>
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:33:25.013124 #14396] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Unmonitored: 2609"]
NoMethodError undefined method `new' for #<Logger:0x00000003d09bb8>
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:33:25.017338 #14396] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Uptime: 82176"]
NoMethodError undefined method `new' for #<Logger:0x00000003d09bb8>
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:33:25.021432 #14396] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Downtime: 1615"]
NoMethodError undefined method `new' for #<Logger:0x00000003d09bb8>
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:33:25.027617 #14396] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Unmonitored: 2609"]
NoMethodError undefined method `new' for #<Logger:0x00000003d09bb8>
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:33:25.032121 #14396] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Uptime: 82176"]
NoMethodError undefined method `new' for #<Logger:0x00000003d09bb8>
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:33:25.036779 #14396] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Downtime: 1615"]
NoMethodError undefined method `new' for #<Logger:0x00000003d09bb8>
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:33:25.043338 #14396] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Unmonitored: 2609"]
NoMethodError undefined method `new' for #<Logger:0x00000003d09bb8>
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:33:25.052963 #14396] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Uptime: 82176"]
NoMethodError undefined method `new' for #<Logger:0x00000003d09bb8>
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:33:25.061728 #14396] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Downtime: 1615"]
NoMethodError undefined method `new' for #<Logger:0x00000003d09bb8>
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:33:25.068197 #14396] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Unmonitored: 2609"]
NoMethodError undefined method `new' for #<Logger:0x00000003d09bb8>
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:33:25.072010 #14396] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Uptime: 82176"]
NoMethodError undefined method `new' for #<Logger:0x00000003d09bb8>
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:33:25.075956 #14396] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Downtime: 1615"]
NoMethodError undefined method `new' for #<Logger:0x00000003d09bb8>
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2017-09-20T15:33:25.081978 #14396] ERROR -- : Sucker Punch job error for class: 'LogJob' args: ["Performance Unmonitored: 2609"]
NoMethodError undefined method `new' for #<Logger:0x00000003d09bb8>
/home/diego/workspace/up_time_reports/app/jobs/log_job.rb:5:in `perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:54:in `__run_perform'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/sucker_punch-2.0.4/lib/sucker_punch/job.rb:36:in `block in perform_async'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/diego/.rvm/gems/ruby-2.4.1@rails-5.1.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
